{% set version = "1.3.1" %}
{% set cov_fail_under = "65" %}
{% set pytest_skip = "test_code_actions or test_completion or test_diagnostics or test_inline_value or test_progress or test_request_error_reporting" %}

package:
  name: pygls
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/p/pygls/pygls-{{ version }}.tar.gz
    sha256: 140edceefa0da0e9b3c533547c892a42a7d2fd9217ae848c330c53d266a55018
  - folder: src
    url: https://github.com/openlawlibrary/pygls/archive/refs/tags/v{{ version }}.tar.gz
    sha256: d2dc2b8e298cac8d3945b237cff1f103b0bf6349f0308361b0041dcdae59ab2f

build:
  number: 1
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - python >={{ python_min }}
    - cattrs >=23.1.2
    - lsprotocol ==2023.0.1

test:
  requires:
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}
  imports:
    - pygls
  commands:
    - pip check
    - pip list
    - pip list | grep -iE 'pygls\s+{{ version.replace("\\", "\\\\") }}$'

outputs:
  - name: pygls

  - name: pygls-with-ws
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pygls", max_pin="x.x.x") }}
        - websockets >=11.0.3
    test:
      source_files:
        - src/tests
      requires:
        - coverage
        - pip
        - pytest <8
        - pytest-asyncio
        - pytest-timeout
        - python {{ python_min }}
      imports:
        - pygls
      commands:
        - pip check
        - cd src
        - pytest --color=yes --collect-only -k "not ({{ pytest_skip }})"
        - coverage run --source=pygls --parallel --branch -m pytest -ra -vv --color=yes --timeout=20 --asyncio-mode=auto -k "not ({{ pytest_skip }})"
        - coverage combine
        - coverage report --show-missing --skip-covered --fail-under={{ cov_fail_under }}

about:
  home: https://pygls.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - dist/LICENSE.txt
    - src/ThirdPartyNotices.txt
  summary: a pythonic generic language server (pronounced like "pie glass").
  description: |
    pygls (pronounced like "pie glass") is a pythonic generic implementation of
    the Language Server Protocol for use as a foundation for writing language
    servers using Python (e.g. Python, XML, etc.). It allows you to write your
    own language server in just a few lines of code.
  dev_url: https://github.com/openlawlibrary/pygls
  doc_url: https://pygls.readthedocs.io
  doc_source_url: https://github.com/openlawlibrary/pygls/tree/master/docs/source

extra:
  feedstock-name: pygls
  recipe-maintainers:
    - bollwyvl
