{% set version = "1.3.0" %}
{% set min_python = "python >=3.8" %}
{% set cov_fail_under = "66" %}
{% set pytest_skip = "test_code_actions or test_completion or test_diagnostics or test_inline_value or test_progress or test_request_error_reporting" %}

package:
  name: pygls
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pygls/pygls-{{ version }}.tar.gz
    sha256: 1b44ace89c9382437a717534f490eadc6fda7c0c6c16ac1eaaf5568e345e4fb8
  - folder: src
    url: https://github.com/openlawlibrary/pygls/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 48596f255a8c49b3a90c8ec1c476e1797d12695e3509b63274042f2be22c68fd

build:
  noarch: python
  number: 0

requirements:
  host:
    - {{ min_python }}
  run:
    - {{ min_python }}

outputs:
  - name: pygls
    build:
      noarch: python
      script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - {{ min_python }}
        - poetry-core
      run:
        - {{ min_python }}
        - cattrs >=23.1.2
        - lsprotocol ==2023.0.1
    test:
      requires:
        - m2-grep  # [win]
        - pip
      imports:
        - pygls
      commands:
        - pip check
        - pip list
        - pip list | grep -iE 'pygls\s+{{ version.replace("\\", "\\\\") }}$'

  - name: pygls-with-ws
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("pygls", max_pin="x.x.x") }}
        - websockets >=11.0.3
    test:
      source_files:
        - src/tests
      requires:
        - coverage
        - pip
        - pytest
        - pytest-asyncio
        - pytest-timeout
      imports:
        - pygls
      commands:
        - pip check
        - cd src
        - pytest --color=yes --collect-only -k "not ({{ pytest_skip }})"
        - coverage run --source=pygls --parallel --branch -m pytest -ra -vv --color=yes --timeout=20 --asyncio-mode=auto -k "not ({{ pytest_skip }})"
        - coverage combine
        - coverage report --show-missing --skip-covered --fail-under={{ cov_fail_under }}
about:
  home: https://pygls.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - dist/LICENSE.txt
    - src/ThirdPartyNotices.txt
  summary: a pythonic generic language server (pronounced like "pie glass").
  description: |
    pygls (pronounced like "pie glass") is a pythonic generic implementation of
    the Language Server Protocol for use as a foundation for writing language
    servers using Python (e.g. Python, XML, etc.). It allows you to write your
    own language server in just a few lines of code.
  dev_url: https://github.com/openlawlibrary/pygls
  doc_url: https://pygls.readthedocs.io
  doc_source_url: https://github.com/openlawlibrary/pygls/tree/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
