{% set version = "1.2.0" %}
{% set cov_fail_under = "67" %}
{% set pytest_skip = "test_code_actions or test_completion or test_diagnostics or test_inline_value or test_progress_notifications" %}

package:
  name: pygls
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pygls/pygls-{{ version }}.tar.gz
    sha256: 72ec4a3532741be1a933c686ed1e138b9948af174213745527a7c3ed3147a573
  - folder: src
    url: https://github.com/openlawlibrary/pygls/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 8850591afb58a6a1e5e077676f6d3918c7773117409081be3cb97737768f951f

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7.9
  run:
    - python >=3.7.9

outputs:
  - name: pygls
    build:
      noarch: python
      script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - python >=3.7.9
        - poetry-core
      run:
        - python >=3.7.9
        - lsprotocol ==2023.0.0
    test:
      requires:
        - m2-grep  # [win]
        - pip
      imports:
        - pygls
      commands:
        - pip check
        - pip list
        - pip list | grep -iE 'pygls\s+{{ version.replace("\\", "\\\\") }}$'

  - name: pygls-with-ws
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7.9
      run:
        - {{ pin_subpackage("pygls", max_pin="x.x.x") }}
        - python >=3.7.9
        - websockets >=11.0.3,<12.0.0
    test:
      source_files:
        - src/tests
      requires:
        - coverage
        - pip
        - pytest
        - pytest-asyncio
        - pytest-timeout
      imports:
        - pygls
      commands:
        - pip check
        - cd src
        - pytest --color=yes --collect-only -k "not ({{ pytest_skip }})"
        - coverage run --source=pygls --parallel --branch -m pytest -ra -vv --color=yes --timeout=20 --asyncio-mode=auto -k "not ({{ pytest_skip }})"
        - coverage combine
        - coverage report --show-missing --skip-covered --fail-under={{ cov_fail_under }}
about:
  home: https://pygls.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - dist/LICENSE.txt
    - src/ThirdPartyNotices.txt
  summary: a pythonic generic language server (pronounced like "pie glass").
  description: |
    pygls (pronounced like "pie glass") is a pythonic generic implementation of
    the Language Server Protocol for use as a foundation for writing language
    servers using Python (e.g. Python, XML, etc.). It allows you to write your
    own language server in just a few lines of code.
  dev_url: https://github.com/openlawlibrary/pygls
  doc_url: https://pygls.readthedocs.io
  doc_source_url: https://github.com/openlawlibrary/pygls/tree/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
